version: '3.8'

services:
  # Vector Database
  chromadb:
    image: chromadb/chroma:latest
    container_name: multimodal_rag_chromadb
    ports:
      - "8001:8000"
    volumes:
      - ./data/chroma_db:/chroma/chroma
    environment:
      - IS_PERSISTENT=TRUE
      - ANONYMIZED_TELEMETRY=FALSE
    networks:
      - rag-network

  # Redis Cache
  redis:
    image: redis:7-alpine
    container_name: multimodal_rag_redis
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    networks:
      - rag-network

networks:
  rag-network:
    driver: bridge

volumes:
  redis_data:
