name: Deploy to Railway

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      
      - name: Install Railway CLI
        run: npm install -g @railway/cli
      
      - name: Deploy to Railway
        env:
          RAILWAY_TOKEN: ${{ secrets.RAILWAY_TOKEN }}
        run: |
          railway up --service app
          
      - name: Deployment notification
        if: success()
        run: |
          echo "✅ Deployment to Railway successful!"
          echo "Check Railway dashboard for deployment details."
      
      - name: Deployment failed
        if: failure()
        run: |
          echo "❌ Deployment to Railway failed!"
          echo "Check logs for details."
